/**
 * Phase 12A — canonical GRPC-1…GRPC-15 roster (metadata only).
 * Full step content ships per-lesson in Phase 12H; GRPC-1 is the pilot implementation.
 */
import {
  GRPC_DEMO_DOCKER_COMMAND,
  GRPC_DEMO_PREREQUISITE_ENDPOINTS,
  GRPC_EXPRESS_HEALTH_URL,
  GRPC_SPRING_DOCKER_COMMAND,
  GRPC_SPRING_FIXTURE_ACTUATOR_HEALTH_URL,
  GRPC_STUDIO_LESSON_ALLOWED_TABS,
  GRPC_TRANSPORT_MODES_PREREQUISITE_ENDPOINTS,
} from './rosterFixtures';
import type { GrpcLessonRosterEntry } from './types';
import { GRPC_LESSON_SCHEMA_VERSION } from './types';

const GO_ECHO_FIXTURE = {
  requireGoEcho: true,
  requireExpressProxy: true,
} as const;

const GO_ECHO_DOCKER = {
  dockerEndpoints: [...GRPC_DEMO_PREREQUISITE_ENDPOINTS],
  dockerCommand: GRPC_DEMO_DOCKER_COMMAND,
  gateLabel: '🐳 Local setup required',
  tag: '🐳 Docker',
} as const;

const STUDIO_TABS = [...GRPC_STUDIO_LESSON_ALLOWED_TABS] as const;

/** Immutable lesson ids — do not rename entries; append migrations in `versioning.ts`. */
export const GRPC_LESSON_ROSTER: readonly GrpcLessonRosterEntry[] = [
  {
    number: 1,
    id: 'grpc-first-call',
    title: 'Your First gRPC Call',
    keyConcept: 'Unary RPC, service explorer',
    phaseDependencies: [1],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
  {
    number: 2,
    id: 'grpc-server-reflection',
    title: 'Service Discovery with Reflection',
    keyConcept: 'Reflection API',
    phaseDependencies: [1, 3],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
  {
    number: 3,
    id: 'grpc-proto-import',
    title: 'Importing Proto Files',
    keyConcept: 'Proto management',
    phaseDependencies: [3],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 4,
    id: 'grpc-metadata',
    title: 'Request Metadata & Headers',
    keyConcept: 'Metadata key-value',
    phaseDependencies: [1],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
  {
    number: 5,
    id: 'grpc-tls',
    title: 'TLS, mTLS & Certificate Configuration',
    keyConcept: 'TLS/mTLS modal, CA cert, client cert, secret vault',
    phaseDependencies: [4],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 6,
    id: 'grpc-server-streaming',
    title: 'Server Streaming RPC',
    keyConcept: 'Message log',
    phaseDependencies: [2],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 7,
    id: 'grpc-client-streaming',
    title: 'Client Streaming RPC',
    keyConcept: 'EOF / send multiple',
    phaseDependencies: [2],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 8,
    id: 'grpc-bidi-streaming',
    title: 'Bidirectional Streaming',
    keyConcept: 'Full duplex',
    phaseDependencies: [2],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 9,
    id: 'grpc-collections',
    title: 'Saving & Organizing Requests',
    keyConcept: 'Collections tree',
    phaseDependencies: [5],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
  {
    number: 10,
    id: 'grpc-env-variables',
    title: 'Environments & Variables',
    keyConcept: '{{grpcHost}}',
    phaseDependencies: [9],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'planned',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: [...STUDIO_TABS, 'environments'],
    estimatedMinutes: 5,
  },
  {
    number: 11,
    id: 'grpc-workflow-integration',
    title: 'gRPC in Workflows: Nodes, Assertions & Chaining',
    keyConcept: 'Workflow node',
    phaseDependencies: [6],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'workflow',
    allowedTabs: [...STUDIO_TABS, 'workflow'],
    estimatedMinutes: 7,
  },
  {
    number: 12,
    id: 'grpc-load-testing',
    title: 'Load Testing: Concurrent Calls & Metrics',
    keyConcept: 'ghz-style metrics',
    phaseDependencies: [11],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 13,
    id: 'grpc-mock-server',
    title: 'Mocking gRPC APIs: Rules & Network Listener',
    keyConcept: 'Rule-based mock responses',
    phaseDependencies: [11],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 10,
  },
  {
    number: 14,
    id: 'grpc-schema-diff',
    title: 'Proto Schema Diff & Breaking Change Detection',
    keyConcept: 'Breaking-change detection',
    phaseDependencies: [11],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 7,
  },
  {
    number: 15,
    id: 'grpc-spring-boot',
    title: 'Spring Boot & Spring gRPC Integration',
    keyConcept: 'Netty vs Servlet transport behavior',
    phaseDependencies: [1, 4, 10],
    fixtures: {
      requireSpringBoot: true,
      requireExpressProxy: true,
    },
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    dockerEndpoints: [
      GRPC_EXPRESS_HEALTH_URL,
      // Actuator on :8081 is the reliable HTTP health probe for the Spring Boot
      // container — it also backs the :9090 gRPC (Netty) port on the same JVM.
      GRPC_SPRING_FIXTURE_ACTUATOR_HEALTH_URL,
    ],
    dockerCommand: GRPC_SPRING_DOCKER_COMMAND,
    gateLabel: '🐳 Local setup required',
    tag: '🐳 Docker',
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 6,
  },
  {
    number: 16,
    id: 'grpc-schema-discovery',
    title: 'Schema Discovery: Reflection & Proto Import',
    keyConcept: 'Descriptor sources, Schema Browser',
    phaseDependencies: [1, 3],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 9,
  },
  {
    number: 17,
    id: 'grpc-streaming',
    title: 'Streaming RPCs: All Four Patterns',
    keyConcept: 'Server, client, and bidi streaming',
    phaseDependencies: [1, 2],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 7,
  },
  {
    number: 18,
    id: 'grpc-metadata-auth',
    title: 'Request Metadata & Authentication',
    keyConcept: 'Metadata headers, bearer/basic/API key/OAuth2 auth, conflict detection',
    phaseDependencies: [1],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 19,
    id: 'grpc-transport-modes',
    title: 'Transport Modes: Express, gRPC-Web & Spring Servlet',
    keyConcept: 'Browser proxy model, gRPC-Web/Spring Servlet browser-direct transports, Express retry fallback, per-tab config',
    phaseDependencies: [1, 10],
    fixtures: {
      ...GO_ECHO_FIXTURE,
      requireEnvoyGrpcWeb: true,
    },
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    // Override: GRPC-19 also needs the Envoy grpc-web sidecar on :50055.
    dockerEndpoints: [...GRPC_TRANSPORT_MODES_PREREQUISITE_ENDPOINTS],
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 6,
  },
  {
    number: 20,
    id: 'grpc-proto-form',
    title: 'Full Form Editor: Guided Complex Request Editing',
    keyConcept: 'Open Full Form Editor modal; Form View / Focus View / JSON View; scalar/nested/repeated/map/oneof/WKT; Apply to Request',
    phaseDependencies: [1, 3],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 5,
  },
  {
    number: 21,
    id: 'grpc-env-collections',
    title: 'Environments, Collections & History',
    keyConcept: '{{grpcHost}} target interpolation, Workspace Defaults variables, Collections tree, History replay',
    phaseDependencies: [5, 9],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    // Land on Environments — step 1 is EM; bouncing through Studio first flashes.
    initialTab: 'environments',
    allowedTabs: [...STUDIO_TABS, 'environments'],
    estimatedMinutes: 6,
  },
  {
    number: 22,
    id: 'grpc-grpcurl',
    title: 'grpcurl Interop, Replay & Sharing',
    keyConcept: 'Import grpcurl command, Studio field mapping, Copy grpcurl from History, secret filtering',
    phaseDependencies: [5, 9],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
  {
    number: 23,
    id: 'grpc-tauri-desktop',
    title: 'Tauri Desktop: Native Transport, Diagnostics & Mock Listener',
    keyConcept: 'Tauri native tonic transport, channel pool diagnostics, mock network listener',
    phaseDependencies: [12],
    fixtures: {
      requireGoEcho: true,
      requiresTauri: true,
    },
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    tag: '🖥️ Desktop only',
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 6,
  },
  {
    number: 24,
    id: 'grpc-workflow-runner',
    title: 'Workflow Runner & Results',
    keyConcept: 'Workflow variables, grpcTarget override, Workflow Runner, Results Dashboard, Results Explorer',
    phaseDependencies: [11],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'workflow',
    allowedTabs: [...STUDIO_TABS, 'workflow', 'workflow-runner', 'results'],
    estimatedMinutes: 10,
  },
  {
    number: 25,
    id: 'grpc-tabs',
    title: 'Multi-Tab gRPC Calls',
    keyConcept: 'Per-tab method binding, duplicate tab, independent responses',
    phaseDependencies: [5],
    fixtures: GO_ECHO_FIXTURE,
    implementationStatus: 'shipped',
    introducedInSchemaVersion: 1,
    ...GO_ECHO_DOCKER,
    initialTab: 'grpc-studio',
    allowedTabs: STUDIO_TABS,
    estimatedMinutes: 4,
  },
] as const;

export const GRPC_LESSON_ROSTER_BY_ID: Readonly<Record<string, GrpcLessonRosterEntry>> =
  Object.fromEntries(GRPC_LESSON_ROSTER.map((entry) => [entry.id, entry]));

export function getGrpcLessonRosterEntry(id: string): GrpcLessonRosterEntry | undefined {
  return GRPC_LESSON_ROSTER_BY_ID[id];
}

/** Roster rows that must have a shipped `GrpcDemoLesson` wrapper in `grpcLessons`. */
export function shippedGrpcLessonRosterEntries(): GrpcLessonRosterEntry[] {
  return GRPC_LESSON_ROSTER.filter((e) => e.implementationStatus === 'shipped');
}

export function assertRosterSchemaVersion(): void {
  for (const entry of GRPC_LESSON_ROSTER) {
    if (entry.introducedInSchemaVersion > GRPC_LESSON_SCHEMA_VERSION) {
      throw new Error(
        `Roster entry ${entry.id} introducedInSchemaVersion ${entry.introducedInSchemaVersion} `
        + `exceeds GRPC_LESSON_SCHEMA_VERSION ${GRPC_LESSON_SCHEMA_VERSION}`,
      );
    }
  }
}
