/**
 * Test Harness selectors — Feature Groups, Test Editor, Runners, Results.
 * Incrementally expanded as lessons are implemented (TH-1 through TH-21).
 */
export const HAR = {
  // ── Navigation ──────────────────────────────────────────────────
  NAV_HARNESS:         '[data-testid="nav-harness"]',
  NAV_SCENARIOS:       '[data-testid="nav-tab-scenarios"]',
  NAV_RUNNER:          '[data-testid="nav-tab-runner"]',
  NAV_PARAM_RUNNER:    '[data-testid="nav-tab-param-runner"]',
  NAV_WF_RUNNER:       '[data-testid="nav-tab-workflow-runner"]',
  NAV_RESULTS:         '[data-testid="nav-tab-results"]',

  // ── Feature Groups (Scenario Builder) ───────────────────────────
  PAGE_HEADER:         '[data-testid="har-page-header"]',
  ADD_FG_BTN:          '[data-testid="har-add-fg-btn"]',
  IMPORT_BTN:          '[data-testid="har-import-btn"]',
  EXPORT_BTN:          '[data-testid="har-export-btn"]',
  TRASH_BTN:           '[data-testid="har-trash-btn"]',
  SHARED_DS_BTN:       '[data-testid="har-shared-ds-btn"]',
  SEARCH_BAR:          '[data-testid="har-search-bar"]',
  FEATURE_TREE:        '[data-testid="har-feature-tree"]',
  EMPTY_STATE:         '[data-testid="har-empty-state"]',
  TREE_SUMMARY:        '[data-testid="har-tree-summary"]',

  // ── Feature Group Card ──────────────────────────────────────────
  FG_CARD:             '[data-testid="har-fg-card"]',
  FG_EXPAND:           '[data-testid="har-fg-expand"]',
  FG_NAME:             '[data-testid="har-fg-name"]',
  FG_ACTIONS:          '[data-testid="har-fg-actions"]',
  FG_NAME_INPUT:       '[data-testid="har-fg-name-input"]',

  // ── Scenario Card ───────────────────────────────────────────────
  SCENARIO_CARD:       '[data-testid="har-scenario-card"]',
  SCENARIO_HEADER:     '[data-testid="har-scenario-header"]',
  SCENARIO_BODY:       '.scenario-group-body',
  ADD_SCENARIO_BTN:    '[data-testid="har-add-scenario-btn"]',
  SCENARIO_NAME_INPUT: '[data-testid="har-scenario-name-input"]',

  // ── Test Card ───────────────────────────────────────────────────
  TEST_CARD:           '[data-testid="har-test-card"]',
  ADD_TEST_BTN:        '[data-testid="har-add-test-btn"]',
  ADD_PARAM_TEST_BTN:  '[data-testid="har-add-param-test-btn"]',
  TEST_EDIT_BTN:       '[data-testid="har-test-edit-btn"]',
  TEST_COPY_BTN:       '[data-testid="har-test-copy-btn"]',
  TEST_MOVE_BTN:       '[data-testid="har-test-move-btn"]',

  // ── Test Editor Modal ─────────────────────────────────────────
  TE_PROP_CARD:        '.te-prop-card',
  TE_NAME_INPUT:       '[data-testid="te-name-input"]',
  TE_URL_INPUT:        '.url-input',
  TE_METHOD_TRIGGER:   '.te-method-trigger',
  TE_TABS:             '.builder-tabs',
  TE_HISTORY_TAB:      '[data-testid="har-te-history-tab"]',
  TE_HEADERS_SECTION:  '.kv-section',
  TE_VALIDATION_SEC:   '.body-validation-section',
  TE_FETCH_BTN:        '.fetch-host-override-row .btn-accent',
  TE_RESPONSE_PREVIEW: '.validation-response-preview',
  TE_SAVE_BTN:         '[data-testid="te-save-btn"]',
  TE_CANCEL_BTN:       '[data-testid="te-cancel-btn"]',
  TE_PARAMETERIZE_BTN: '[data-testid="te-parameterize-btn"]',

  // ── Validation Tab (TH-3) ─────────────────────────────────────
  TE_RADIO_GROUP:      '.body-validation-section .radio-group',
  TE_ASSERTIONS_SECTION: '.assertions-section',
  TE_ASSERTIONS_ADD_BTN: '.assertions-add-wrap .btn-accent',
  TE_ASSERTIONS_ADD_MENU: '.assertions-add-menu',
  TE_ASSERTIONS_LIST:  '.assertions-list',
  TE_ASSERTION_ROW:    '.assertion-row',
  TE_VERIFY_BTN:       '.btn-validate',
  TE_VERIFY_RESULT:    '.validate-result',
  TE_HOST_OVERRIDE:    '.validate-response-row .fetch-host-toggle',
  TE_HOST_INPUT:       '.validate-host-input',
  TE_VALIDATION_RULES: '.validation-fields-summary',
  TE_MAPPER_BTN:       '.fetch-host-override-row .btn-accent:last-of-type',

  // ── Test Runner (TH-4) ────────────────────────────────────────
  HOST_SELECTOR:       '[data-testid="har-host-selector"]',
  HOST_MOCK_SERVER:    '[data-testid="har-host-mock"]',
  /** Host radios + API Mock fixture — keep this cluster on screen for Isolate. */
  RUNNER_MOCK_SETUP:   '[data-testid="har-runner-mock-setup"]',
  HOST_CUSTOM_INPUT:   '.runner-custom-url-input',
  EXEC_CONFIG:         '[data-testid="har-exec-config"]',
  ARRIVAL_RAMP_FIELDS: '[data-testid="har-arrival-ramp-fields"]',
  SCENARIO_SELECTOR:   '[data-testid="har-scenario-selector"]',
  EXEC_PLAN:           '[data-testid="har-exec-plan"]',
  RUN_BTN:             '[data-testid="har-run-btn"]',
  STOP_BTN:            '[data-testid="har-stop-btn"]',
  LIVE_PROGRESS:       '[data-testid="har-live-progress"]',
  COMPLETION:          '[data-testid="har-completion"]',
  VIEW_RESULTS_BTN:    '[data-testid="har-view-results"]',
  HARNESS_MOCK_FIXTURE: '[data-testid="har-apimock-fixture"]',
  HARNESS_MOCK_SERVER:  '[data-testid="har-apimock-fixture-server"]',
  HARNESS_MOCK_ISOLATE: '[data-testid="har-apimock-fixture-isolate"]',
  HARNESS_MOCK_ISOLATE_ROW: '[data-testid="har-apimock-fixture-isolate-row"]',
  HARNESS_MOCK_START:   '[data-testid="har-apimock-fixture-start"]',
  HARNESS_MOCK_STOPPED: '[data-testid="har-apimock-fixture-stopped"]',
  HARNESS_MOCK_PORT:    '[data-testid="har-apimock-fixture-port"]',
  HARNESS_MOCK_FREED_PORT: '[data-testid="har-apimock-fixture-freed-port"]',

  // ── Data Source (TH-5) ────────────────────────────────────────
  DS_GRID:             '.data-source-grid',
  DS_TOOLBAR:          '.data-source-toolbar-unified',
  DS_FROM_API_BTN:     '.data-source-toolbar-unified .data-source-toolbar-btn[title*="map fields into data-source"]',
  DS_MAP_COLUMNS_BTN:  '.data-source-toolbar-unified .data-source-toolbar-btn[title*="Data Mapper"]',
  TE_DS_TAB:           '[data-testid="har-te-ds-tab"]',
  DS_ADD_ROW_BTN:      '.data-source-toolbar-btn[title="Add a new row"]',
  DS_ADD_COL_BTN:      '.data-source-toolbar-btn[title="Add a new column"]',
  DS_ROW:              '.data-source-row',
  DS_CELL_INPUT:       '.data-source-cell-input',
  DS_COL_HEADER:       '.data-source-col-header',
  DS_COL_MAPPING:      '[data-testid="ds-col-mapping"]',
  DS_COL_TYPE_SELECT:  '.data-source-col-type-select',
  DS_TAG_ADD_BTN:      '.data-source-tag-add-btn',
  DS_TAG_PILL:         '.data-source-tag-pill',
  DS_TAG_INPUT:        '.data-source-tag-input',
  DS_TAG_FILTER_BAR:   '.data-source-tag-filter-bar',
  DS_TAG_FILTER_BTN:   '.data-source-tag-filter-btn',
  DS_SEARCH_COUNT:     '.data-source-search-count',
  DS_SAVE_SUBSET:      '.data-source-save-subset',
  DS_FOOTER:           '.data-source-footer',
  DS_PREVIEW:          '.data-source-preview',
  DS_VERIFY_OPEN_BTN:  '.data-source-toolbar-unified .data-source-toolbar-btn[title*="Verify"]',
  DS_ROW_CHECKBOX:     '.params-toggle',
  DS_EMPTY_STATE:      '.data-source-empty',
  DS_PARAM_BADGE:      '.kind-badge-param',
  TEST_PARAM_BADGE:    '.test-card .parameterized-tag',

  // ── Execution Config Advanced (TH-8) ────────────────────────
  EXEC_MODE_ROW:       '[data-testid="har-exec-mode"]',
  EXEC_MODE_LOAD_PROFILE: '[data-testid="har-exec-mode-load-profile"]',
  RUNTIME_PARAMS:      '[data-testid="har-runtime-params"]',
  ERROR_POLICY_ROW:    '[data-testid="har-error-policy-row"]',
  LOAD_PROFILE_SEC:    '.load-profile-section',
  PROFILE_TYPE_SEL:    '.profile-type-selector',
  PROFILE_TYPE_BTN:    '.profile-type-btn',
  PROFILE_TYPE_DESC:   '.profile-type-desc',
  PROFILE_PREVIEW:     '.profile-preview-container',
  PROFILE_FIELDS:      '.profile-fields',
  THINK_TIME_SEC:      '[data-testid="har-think-time"]',
  RESILIENCE_ROW:      '.resilience-config',
  ERROR_POLICY:        '.error-policy-options',

  // ── Parameterized Runner (TH-6) ─────────────────────────────
  PARAM_PAGE_HEADER:   '.param-runner-page .page-header',
  WEIGHTS_FIELDSET:    '[data-testid="har-weights-section"]',
  WEIGHTS_LEGEND:      '.collapsible-legend',
  WEIGHT_ROW:          '.weight-row',
  WEIGHT_INPUT:        '.weight-input',
  WEIGHT_RESET_1:      '[data-testid="har-weights-reset-1"]',
  WEIGHT_RESET_0:      '[data-testid="har-weights-reset-0"]',
  TAG_FILTER_INPUT:    '.runner-tag-filter-input',
  TAG_FILTER_HINT:     '.runner-tag-filter-hint',
  TAG_FILTER_FIELDSET: '.runner-fieldset',
  PER_TEST_PROGRESS:   '.runner-per-test-progress',
  PER_TEST_ROW:        '.runner-per-test-row',
  LIVE_METRICS:        '.live-metrics',
  METRIC_CARD:         '.metric-card',

  // ── Results Dashboard (TH-7) ────────────────────────────────
  RESULTS_TOP:         '.results-top',
  RUN_TYPE_TABS:       '.results-run-filter-tabs',
  RUN_TYPE_TAB:        '.run-filter-tab',
  RUN_SELECT:          '.results-run-select',
  RUN_SELECT_TRIGGER:  '.results-run-select-trigger',
  RUN_SELECT_MENU:     '.results-run-select-menu',
  RUN_SELECT_OPTION:   '.results-run-select-option',
  VIEW_TABS:           '.results-view-tabs',
  VIEW_TAB:            '.results-view-tab',
  TAB_OVERVIEW:        '#results-tab-overview',
  TAB_REQUESTS:        '#results-tab-requests',
  TAB_SLA:             '#results-tab-sla',
  TAB_ANALYSIS:        '#results-tab-analysis',
  METRICS_CARDS:       '[data-testid="results-metrics-cards"]',
  METRICS_LATENCY:     '[data-testid="results-metrics-latency-row"]',
  HISTOGRAM:           '.histogram-container',
  TIMING_TABLE:        '.wf-agg-table',
  GROUP_BY:            '.group-by-controls',
  BASELINE_TOGGLE:     '.baseline-toggle',
  EXPORT_JSON:         '[data-testid="results-export-json-btn"]',
  REPORT_MENU:         '.report-menu-wrapper',
  REPORT_MENU_BTN:     '.report-menu-wrapper > .btn',
  REPORT_DROPDOWN:     '.report-menu-dropdown',
  REPORT_MENU_ITEM:    '.report-menu-item',
  SLA_PANEL:           '.sla-status-panel',
  SLA_COMPACT:         '.sla-compact-bar',
  RERUN_FAILED_BAR:    '.rerun-failed-bar',

  // ── Organization & Versioning (TH-9) ──────────────────────
  SEARCH_WRAPPER:      '.builder-search-wrapper',
  SEARCH_INPUT:        '.builder-search-input',
  SEARCH_COUNT:        '.builder-search-count',
  SEARCH_MATCH:        '.test-card.search-match',
  TAG_PILL:            '.scenario-tag-pill',
  TAG_ADD_BTN:         '.scenario-tag-add-btn',
  TAG_INPUT:           '.scenario-tag-input',
  VERSION_PANEL:       '[data-testid="version-history-panel"]',
  VERSION_ITEM:        '[data-testid="version-item"]',
  VERSION_COMPARE_BTN: '[data-testid="version-compare-btn"]',
  VERSION_RESTORE_BTN: '[data-testid="version-restore-btn"]',
  VERSION_CLEAR_SELECTION: '.test-def-version-footer-clear',
  /** App-wide workflow toast stack (e.g. version restore confirmation). */
  WF_TOAST:            '.wf-toast',
  /** Test-definition version compare modal (History tab → Compare). */
  TEST_DEF_DIFF_MODAL: '.test-def-diff-modal',
  TEST_DEF_DIFF_ROW:   '.test-def-diff-row',
  TEST_DEF_DIFF_TAB:   '.test-def-diff-tab',
  TEST_DEF_DIFF_FOOTER:'.test-def-diff-footer',
  TEST_DEF_DIFF_HEADERS_ROW: '.test-def-diff-headers-tr',
  TRASH_TOAST:         '.trash-toast',
  TRASH_TOAST_UNDO:    '.trash-toast-undo',
  TRASH_TOAST_DISMISS: '.trash-toast-dismiss',
  TRASH_PANEL:         '.trash-panel-modal',
  TRASH_ITEM:          '.trash-card',
  TRASH_ITEM_RESTORE:  '.trash-card-restore',
  TRASH_ITEM_DELETE:   '.trash-card-delete',
  TRASH_RETENTION_SELECT: '[data-testid="har-trash-retention"]',
  TRASH_MAX_ITEMS_SELECT: '[data-testid="har-trash-max-items"]',
  TRASH_SELECT_MENU:   '.cs-menu',
  TRASH_EMPTY_BTN:     '[data-testid="har-trash-empty-btn"]',
  TRASH_CONFIRM_MODAL: '.popup-modal',
  /** Cancel in the Empty Trash / permanent-delete confirmation footer. */
  TRASH_CONFIRM_CANCEL: '.popup-modal .popup-modal-footer .btn:not(.btn-danger):not(.btn-primary)',
  TRASH_CONFIRM_EMPTY:  '.popup-modal .popup-modal-footer .btn-danger',
  TEST_DELETE_BTN:     '.test-card-actions .btn-danger',
  TEST_ACTIONS:        '.test-card-actions',

  // ── Assertions Deep Dive (TH-10) ──────────────────────────
  TE_ASSERTION_BADGE:    '.assertion-type-badge',
  TE_ASSERTION_NOT:      '.assertion-negate-toggle',
  TE_ASSERTION_SCHEMA:   '.assertion-field--schema',
  TE_SCHEMA_TOOLBAR:     '.assertion-schema-toolbar',
  TE_SCHEMA_GENERATE:    '.assertion-schema-action',
  TE_CUSTOM_EXPR:        '.assertion-input--expression-inline',
  TE_CUSTOM_DESC:        '.assertion-input--desc-inline',
  TE_JPP_BTN:            '.jpp-btn',
  TE_JPP_MENU:           '.jpp-menu',
  TE_JPP_ITEM:           '.jpp-item',
  TE_PRESETS_WRAP:       '.assertion-preset-wrap',
  TE_PRESETS_MENU:       '.assertion-preset-menu',
  TE_PRESET_CARD:        '.apm-card',
  TE_REGEX_BUILDER_BTN:  '.assertion-builder-btn',
  TE_REGEX_MODAL:        '.ram-modal',
  TE_REGEX_TREE:         '.ram-left',
  TE_REGEX_PATTERN:      '[data-testid="pattern-input"]',
  TE_REGEX_PREVIEW:      '[data-testid="match-preview"]',

  // ── Data Mapper (TH-11) ───────────────────────────────────
  MAPPER_MODAL:          '.dm-modal-overlay',
  MAPPER_SHELL:          '.dm-modal-shell',
  MAPPER_CANCEL_BTN:     '.dm-modal-shell .dm-modal-btn--secondary',
  MAPPER_FULLSCREEN_BTN: '.dm-modal-header-btn',
  MAPPER_SOURCE:         '.dm-panel--source',
  MAPPER_FETCH_SAMPLE:   '[aria-label="Fetch live sample"]',
  MAPPER_SOURCE_TREE:    '.dm-panel--source .dm-tree-container, .dm-panel--source .dm-tree-node',
  MAPPER_TARGET:         '.dm-panel--target',
  MAPPER_CANVAS:         '.dm-canvas',
  MAPPER_TOOLBAR:        '.dm-toolbar',
  MAPPER_AUTOMAP:        '.dm-toolbar-btn--primary',
  MAPPER_CLEAR_ALL:      '.dm-toolbar-btn--danger',
  MAPPER_STATUS:         '.dm-toolbar-status',
  MAPPER_HEALTH:         '.dm-health-dashboard',
  MAPPER_OPERATOR_PILL:  '.dm-operator-pill',
  MAPPER_OPERATOR_PICKER:'.dm-operator-picker',
  MAPPER_VERIFY_BTN:     '.dm-toolbar-btn--verify',
  MAPPER_VERIFY_BADGE:   '.dm-verify-badge',
  MAPPER_VERIFY_SUMMARY: '.dm-toolbar-verify-summary',
  MAPPER_CODE_VIEW:      '.dm-code-view',
  MAPPER_TABLE_VIEW:     '.dm-table-view',
  MAPPER_CODE_BTN:       '[data-testid="dm-view-code"]',
  MAPPER_TABLE_BTN:      '[data-testid="dm-view-table"]',
  MAPPER_RULES_BTN:      '[data-testid="dm-view-rules"]',
  MAPPER_SEARCH:         '.dm-search-input',
  MAPPER_TYPE_PILL:      '.dm-type-pill',
  MAPPER_SAVE_BTN:       '.dm-modal-btn--primary',

  // ── Validation Versioning (TH-12) ─────────────────────────
  RESP_VERSION_PANEL:    '.version-panel',
  RULES_VERSION_PANEL:   '.rules-version-panel',
  VAL_VERSION_ITEM:      '.version-item',
  VAL_VERSION_CURRENT:   '.version-item.version-current',
  VERSION_LABEL:         '.version-label',
  VERSION_TIME:          '.version-time',
  VERSION_CURRENT_TAG:   '.version-current-tag',
  VERSION_RULES_TAG:     '.version-rules-tag',
  VERSION_ACTIONS:       '.version-item-actions',
  VERSION_PREVIEW_MODAL: '.vp-modal',
  VERSION_DIFF_MODAL:    '.version-diff-modal',
  VERSION_DIFF_VIEWER:   '.version-diff-viewer',
  VERSION_DIFF_INFO:     '.version-diff-info-bar',
  VERSION_DIFF_TABS:     '.version-diff-tabs',

  // ── SLA Targets (TH-13) ─────────────────────────────────
  TEST_SLA_BTN:          '[data-testid="har-test-sla-btn"]',
  SLA_MODAL:             '.test-sla-modal',
  SLA_EMPTY_HINT:        '.test-sla-empty-hint',
  SLA_ADD_BTN:           '.test-sla-add-btn',
  SLA_TABLE:             '.test-sla-table',
  SLA_METRIC_SELECT:     '.test-sla-select',
  SLA_OPERATOR:          '.test-sla-operator',
  SLA_INPUT:             '.test-sla-input',
  SLA_DELETE_BTN:        '.test-sla-delete-btn',
  SLA_FOOTER_ACTIONS:    '.test-sla-footer-actions',
  SLA_SUMMARY_PANEL:     '.scenario-sla-panel',
  SLA_SUMMARY_TABLE:     '.sla-summary-table',
  SLA_TRIGGER:           '.sla-trigger',
  SLA_TRIGGER_BTN:       '.sla-trigger-btn',
  SLA_OVERRIDE_MODAL:    '.sla-override-modal',

  // ── Auth & Inheritance (TH-14) ──────────────────────────
  AUTH_PANEL:            '.scenario-auth-panel',
  FEATURE_AUTH_PANEL:    '.feature-auth-panel',
  AUTH_TYPE_SELECT:      '.auth-type-select',
  AUTH_INHERIT_HINT:     '.auth-inherit-hint',
  AUTH_PROFILE_SELECT:   '.global-profile-selector',
  AUTH_VERIFY_BTN:       '.auth-verify-section .btn-verify',
  AUTH_VERIFY_RESULT:    '.auth-verify-result',
  AUTH_BADGE:            '.auth-badge',

  // ── Import, Export & cURL (TH-15) ─────────────────────
  CURL_MODE_PANEL:       '.curl-mode-panel',
  CURL_EXPORT_TEXTAREA:  '.curl-export-textarea',
  MODE_TOGGLE:           '.mode-toggle',
  MODE_BTN:              '.mode-btn',
  MODE_DROPDOWN:         '.mode-btn-dropdown',
  MODE_DROPDOWN_ITEM:    '.mode-btn-dropdown-item',
  EXPORT_POPOVER:        '.export-opts-popover',
  EXPORT_POPOVER_CHECK:  '.export-opts-check',
  /** Feature Group card Export (version options) — not scenario/test/toolbar Export */
  FG_EXPORT_BTN:         '[data-testid="har-fg-export-btn"]',
  CSV_IMPORT_MODAL:      '.csv-import-modal',
  AUTO_REPORT_LABEL:     '.selection-actions .checkbox-label',

  // ── Advanced Search & Drag-Drop (TH-16) ────────────────
  DRAG_HANDLE:           '.drag-handle',
  DROP_ZONE:             '.drop-zone-end',
  SEARCH_HELP:           '.search-help',
  SEARCH_HELP_BTN:       '[data-testid="har-search-help-btn"]',
  COPY_MODAL:            '.popup-modal',
  MOVE_MODAL:            '.popup-modal',
  UNASSOCIATED_SECTION:  '.unassociated-section',
  UNASSOCIATED_CARD:     '.unassociated-card',

  // ── Expression Editor & DSL (TH-17) ──────────────────
  EXPR_MODAL:            '.dm-expr-modal',
  EXPR_SIDEBAR:          '.dm-expr-sidebar',
  EXPR_FN_SEARCH:        '.dm-expr-fn-search',
  EXPR_FN_LIST:          '.dm-expr-fn-list',
  EXPR_EDITOR_AREA:      '.dm-expr-editor-area',
  EXPR_DOCS:             '.dm-expr-docs',
  EXPR_PREVIEW:          '.dm-expr-preview-section',
  EXPR_DEBUG_TOGGLE:     '.dm-expr-debug-toggle',
  EXPR_STEP_DEBUGGER:    '.dm-expr-step-debugger',
  EXPR_SNIPPETS:         '.dm-expr-snippets',
  EXPR_TEMPLATES:        '.dm-expr-template-panel',
  EXPR_FOOTER:           '.dm-expr-footer',
  VR_MODAL:              '.vr-modal-panel',
  VR_EDITOR:             '.vr-modal-editor-pane',
  VR_REFERENCE:          '.vr-reference-pane',
  VR_VERIFY_BTN:         '.vr-modal-action-btn--verify',
  VR_STAT_PASS:          '.vr-modal-stat--pass',
  VR_STAT_FAIL:          '.vr-modal-stat--fail',
  VR_RESULTS_STRIP:      '.vr-results-strip',
  VR_VIEW_LINE:          '.vr-modal-editor-pane .view-lines .view-line',
  VR_CURRENT_LINE:       '.vr-modal-editor-pane .current-line',

  // ── Data Source Advanced (TH-18) ─────────────────────
  ROW_DETAIL_MODAL:      '.row-detail-modal',
  ROW_DETAIL_FETCH:      '.row-detail-fetch-btn',
  ROW_DETAIL_URL:        '.row-detail-url-preview',
  ROW_DETAIL_FIELD:      '.row-detail-field',
  ROW_DETAIL_FETCH_CONFIRM: '.fetch-confirm-bar',
  ROW_DETAIL_KEEP_RULES: '[data-testid="row-detail-keep-rules"]',
  ROW_DETAIL_VALIDATION_TABLE: '.validation-fields-table',
  ROW_EDIT_BTN:          '[data-testid="ds-row-edit-btn"]',
  VERIFY_MODAL:          '.verify-modal',
  VERIFY_RUN_BTN:        '.verify-modal-footer .btn-primary',
  VERIFY_PROGRESS:       '.verify-progress-bar',
  VERIFY_ROW_CARDS:      '.verify-row-cards',
  VERIFY_STATS:          '.verify-stat-pass',
  VERIFY_SUMMARY:        '.verify-summary-bar',
  VERIFY_CARD_PASS:      '.verify-row-card.verify-card-pass',
  VERIFY_ACTUAL_PASS:    '.verify-val-actual.val-pass',
  CONTRACT_PANEL:        '.data-source-contract-panel',
  CONTRACT_BTN:          '.data-source-toolbar-unified .data-source-toolbar-btn[title*="validation contract"]',
  CONTRACT_MODE_BTN:     '.data-source-contract-mode-btn',
  CONTRACT_LIST:         '.data-source-contract-list',
  SHARED_DS_MODAL:       '.shared-ds-modal',
  SHARED_DS_LIST:        '.shared-ds-list-panel',
  SHARED_DS_EDITOR:      '.shared-ds-editor-panel',
  SHARED_DS_FETCH:       '.shared-ds-fetch-panel',
  SHARED_DS_USED_BY:     '.shared-ds-used-by',
  SHARED_DS_GRID:        '.shared-ds-editor-content .data-source-scroll',
  SHARED_DS_USED_BY_TOGGLE: '.shared-ds-used-by-toggle',
  SHARED_DS_USED_BY_LIST: '.shared-ds-used-by-list',
  /** Create Parameterized Copy / data-source setup wizard (opens after cURL Import & Apply). */
  DS_SETUP_DIALOG:       '.ds-setup-dialog',

  // ── Schema Drift & Repair (TH-19) ───────────────────────
  DRIFT_BANNER:          '.dm-drift-banner',
  DRIFT_ACCEPT_BTN:      '.dm-drift-btn--accept',
  DRIFT_DIFF_BTN:        '[data-testid="dm-drift-show-diff"]',
  DIFF_SHELL:            '.dm-diff-shell',
  DIFF_OVERLAY:          '.dm-diff-overlay',
  DIFF_TABLE:            '.dm-diff-table',
  DIFF_SEVERITY:         '.dm-diff-severity',
  DIFF_AFFECTED:         '.dm-diff-affected',
  DIFF_REPAIR_CELL:      '.dm-diff-repair-cell',
  REPAIR_BTN:            '.dm-repair-btn',
  REPAIR_APPLY:          '.dm-repair-apply-btn',
  REPAIR_BATCH:          '.dm-repair-btn--batch',
  VALIDATION_REPAIR_PANEL: '[data-testid="dm-validation-repair-panel"]',
  VALIDATION_REPAIR_ROW: '.dm-validation-repair-row',

  // ── Workflow Runner (TH-21) ────────────────────────────────
  WF_PICKER:             '.workflow-picker',
  WF_PICKER_TRIGGER:     '[data-testid="workflow-select"]',
  WF_PICKER_PANEL:       '.wfp-dropdown-panel',
  WF_PICKER_SEARCH:      '[data-testid="wfp-search-input"]',
  WF_PICKER_ITEM:        '.wfp-dropdown-item',
  WF_PICKER_SUMMARY:     '.workflow-picker-summary',
  WF_VARS_SECTION:       '.workflow-vars-section',
  WF_VARS_GRID:          '.wfp-vars-grid',
  WF_VAR_ROW:            '.wfp-var-row',
  WF_VARS_ACTIONS:       '.workflow-vars-actions',
  WF_VARS_ACTION_BTN:    '.workflow-vars-actions .wfp-action-btn',
  WF_HISTORY_PANEL:      '.workflow-history-panel',
  WF_HISTORY_LIST:       '.history-list',
  WF_HISTORY_ITEM:       '.history-item',
  WF_HISTORY_SAVE_INPUT: '.history-save-input',
  WF_HISTORY_SAVE_FORM:  '.history-save-form',
  WF_TRACE_OPTIONS:      '.wf-runner-inline-options',
  WF_TRACE_RADIO:        '.wf-runner-inline-options input[name="wf-traceLevel"]',
  WF_CONFIG_SECTION:     '.workflow-runner-config-section',
  WF_RUN_BTN:            '[data-testid="workflow-runner-run-btn"]',
  WF_STOP_BTN:           '[data-testid="workflow-runner-stop-btn"]',
  WF_COMPLETION:         '.completion-section',
  WF_CORR_SECTION:       '.wf-runner-correlation-section',
  WF_CORR_MODE:          '.wf-runner-correlation-mode',
  WF_MWT_PANEL:          '.mwt-panel',

  // ── Baseline & Regression (TH-20) ──────────────────────────
  BASELINE_LIST:         '.baseline-list-panel',
  BASELINE_LIST_ITEM:    '.baseline-list-item',
  BASELINE_LIST_ACTIONS: '.baseline-list-actions',
  THRESHOLDS_PANEL:      '.thresholds-panel',
  THRESHOLDS_GRID:       '.thresholds-grid',
  COMPARISON_TOOLBAR:    '.results-comparison-trends-toolbar',
  COMPARISON_MODE_BADGE: '.comparison-mode-badge',
  COMPARE_SELECT:        '.baseline-compare-select',
  COMPARISON_PANEL:      '.run-comparison-panel',
  COMPARISON_TABS:       '.run-comparison-tabs',
  COMPARISON_EXPORT_BTN: '.run-comparison-export-btn',
  COMPARISON_EXPORT_MENU:'.run-comparison-export-menu',
  TREND_CONTAINER:       '.trend-chart-container',
  TREND_TABS:            '.trend-chart-tabs',
  TREND_SCOPE_SELECT:    '.trend-scope-select',
  COMPARISON_LAYOUT:     '.results-comparison-trends-layout',
  COMPARISON_SIDEBAR:    '.results-comparison-trends-side',
} as const;
